package modelo.entidad;
// Generated 10/02/2022 09:39:46 by Hibernate Tools 4.3.1



/**
 * Medico generated by hbm2java
 */
public class Medico  implements java.io.Serializable {


     private Integer idMedico;
     private String nombre;
     private String apellido;
     private int sala;
     private String especialidad;

    public Medico() {
    }

    public Medico(String nombre, String apellido, int sala, String especialidad) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.sala = sala;
       this.especialidad = especialidad;
    }
   
    public Integer getIdMedico() {
        return this.idMedico;
    }
    
    public void setIdMedico(Integer idMedico) {
        this.idMedico = idMedico;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getSala() {
        return this.sala;
    }
    
    public void setSala(int sala) {
        this.sala = sala;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }




}


